// On-screen text in every language (spoken phrases live in i18n.js).
// Have a native speaker check each table before your demo.
import { getLang } from './i18n.js';

const UI = {
  en: {
    tagline: 'The cane that remembers',
    connected: 'Cane connected', demo: 'Demo', offline: 'Not connected',
    demoBanner: 'Demo mode: simulated cane data. Connect to your cane to use it for real.',
    start: 'Start walking', stop: 'Stop walking',
    pathClear: 'Path clear', levels: ['Clear', 'Caution', 'Warning', 'Stop'],
    whereAmI: 'Where am I?', savePlace: 'Save place', hazardGone: 'Hazard gone',
    recentAlerts: 'Recent alerts', noAlerts: 'Alerts you hear will be listed here.',
    corridor: 'Walking corridor', corridorHint: '1 m wide, 4 m ahead. Hollow marks are remembered hazards.',
    helperView: 'Camera view for a helper',
    tabs: ['Walk', 'Places', 'Memory', 'Settings'],
    placesTitle: 'Saved places', placesEmpty: 'No places yet. When you reach a place you visit often, save it with a name.',
    placeName: 'Name of this place', save: 'Save', guideMe: 'Guide me', guiding: 'Guiding to', stopGuide: 'Stop guidance',
    memoryTitle: 'Remembered hazards', hazardsN: 'Hazards', placesN: 'Places', pathPoints: 'Path points',
    memEmpty: 'No hazards remembered yet. They are added automatically when the cane detects one.',
    seen: (n) => `Seen ${n} ${n === 1 ? 'time' : 'times'}`, risk: 'Risk', itsGone: 'It’s gone',
    routeTitle: 'Route to', shortest: 'Shortest', safest: 'Safest', metres: 'm',
    settingsTitle: 'Settings', language: 'Language', speechRate: 'Speaking speed', vibration: 'Vibrate on alerts',
    demoMode: 'Demo mode', demoHint: 'Try the app without the cane, using simulated data.',
    research: 'Research mode', researchHint: 'While walking, tap what the situation really is. This trains the neural network.',
    labels: ['Safe', 'Caution', 'Warning', 'Urgent'], rows: (n) => `${n} labelled rows`,
    exportCsv: 'Download training data', exportMem: 'Download memory',
    resetMemory: 'Erase memory', resetConfirm: 'All remembered hazards, places and paths will be erased.',
    cancel: 'Cancel', confirmErase: 'Erase', chooseLanguage: 'Choose your language', example: 'Example',
    away: (m) => `${m} m away`, ahead: 'ahead', left: 'left', right: 'right',
    justNow: 'just now', minAgo: (n) => `${n} min ago`, hrAgo: (n) => `${n} h ago`, dayAgo: (n) => `${n} ${n === 1 ? 'day' : 'days'} ago`,
    cat: { drop: 'Drop', raised: 'Raised', static: 'Obstacle', head: 'Head height', moving: 'Moving', zone: 'Zone' },
    model: 'Fusion network', modelOn: 'Neural network active', modelOff: 'Rules only',
    connection: 'Connection', fps: 'frames/s',
  },
  hi: {
    tagline: 'छड़ी जो याद रखती है',
    connected: 'छड़ी जुड़ी है', demo: 'डेमो', offline: 'छड़ी नहीं जुड़ी',
    demoBanner: 'डेमो मोड: नकली डेटा. असली उपयोग के लिए अपनी छड़ी से जोड़ें.',
    start: 'चलना शुरू करें', stop: 'चलना रोकें',
    pathClear: 'रास्ता साफ़ है', levels: ['साफ़', 'सावधानी', 'चेतावनी', 'रुकिए'],
    whereAmI: 'मैं कहाँ हूँ?', savePlace: 'जगह सेव करें', hazardGone: 'खतरा हट गया',
    recentAlerts: 'हाल की सूचनाएँ', noAlerts: 'जो सूचनाएँ आप सुनेंगे, वे यहाँ दिखेंगी.',
    corridor: 'चलने का रास्ता', corridorHint: '1 मीटर चौड़ा, 4 मीटर आगे तक. खाली निशान याद रखे गए खतरे हैं.',
    helperView: 'सहायक के लिए कैमरा दृश्य',
    tabs: ['चलें', 'जगहें', 'याददाश्त', 'सेटिंग्स'],
    placesTitle: 'सेव की गई जगहें', placesEmpty: 'अभी कोई जगह नहीं. जहाँ आप अक्सर जाते हैं, वहाँ पहुँचकर उसे नाम से सेव करें.',
    placeName: 'इस जगह का नाम', save: 'सेव करें', guideMe: 'वहाँ ले चलो', guiding: 'रास्ता बता रहे हैं:', stopGuide: 'मार्गदर्शन रोकें',
    memoryTitle: 'याद रखे गए खतरे', hazardsN: 'खतरे', placesN: 'जगहें', pathPoints: 'रास्ते के बिंदु',
    memEmpty: 'अभी कोई खतरा याद नहीं है. छड़ी को खतरा दिखते ही यह अपने आप जुड़ जाता है.',
    seen: (n) => `${n} बार देखा`, risk: 'जोखिम', itsGone: 'हट गया',
    routeTitle: 'रास्ता:', shortest: 'सबसे छोटा', safest: 'सबसे सुरक्षित', metres: 'मी',
    settingsTitle: 'सेटिंग्स', language: 'भाषा', speechRate: 'बोलने की गति', vibration: 'सूचना पर कंपन',
    demoMode: 'डेमो मोड', demoHint: 'बिना छड़ी के, नकली डेटा से ऐप आज़माएँ.',
    research: 'रिसर्च मोड', researchHint: 'चलते समय असली स्थिति चुनें. इससे न्यूरल नेटवर्क सीखता है.',
    labels: ['सुरक्षित', 'सावधानी', 'चेतावनी', 'तुरंत खतरा'], rows: (n) => `${n} पंक्तियाँ`,
    exportCsv: 'ट्रेनिंग डेटा डाउनलोड करें', exportMem: 'याददाश्त डाउनलोड करें',
    resetMemory: 'याददाश्त मिटाएँ', resetConfirm: 'सभी खतरे, जगहें और रास्ते मिट जाएँगे.',
    cancel: 'रद्द करें', confirmErase: 'मिटाएँ', chooseLanguage: 'अपनी भाषा चुनें', example: 'उदाहरण',
    away: (m) => `${m} मी दूर`, ahead: 'सामने', left: 'बाएँ', right: 'दाएँ',
    justNow: 'अभी', minAgo: (n) => `${n} मिनट पहले`, hrAgo: (n) => `${n} घंटे पहले`, dayAgo: (n) => `${n} दिन पहले`,
    cat: { drop: 'गड्ढा/ढलान', raised: 'ऊँचाई', static: 'रुकावट', head: 'सिर की ऊँचाई', moving: 'चलती चीज़', zone: 'क्षेत्र' },
    model: 'फ्यूज़न नेटवर्क', modelOn: 'न्यूरल नेटवर्क चालू', modelOff: 'सिर्फ़ नियम',
    connection: 'कनेक्शन', fps: 'फ्रेम/सेकंड',
  },
  te: {
    tagline: 'గుర్తుంచుకునే కర్ర',
    connected: 'కర్ర కనెక్ట్ అయింది', demo: 'డెమో', offline: 'కర్ర కనెక్ట్ కాలేదు',
    demoBanner: 'డెమో మోడ్: నమూనా డేటా. నిజంగా వాడటానికి మీ కర్రకు కనెక్ట్ చేయండి.',
    start: 'నడక ప్రారంభించండి', stop: 'నడక ఆపండి',
    pathClear: 'దారి స్పష్టంగా ఉంది', levels: ['స్పష్టం', 'జాగ్రత్త', 'హెచ్చరిక', 'ఆగండి'],
    whereAmI: 'నేను ఎక్కడ ఉన్నాను?', savePlace: 'చోటు సేవ్ చేయండి', hazardGone: 'ప్రమాదం తొలగింది',
    recentAlerts: 'ఇటీవలి హెచ్చరికలు', noAlerts: 'మీరు వినే హెచ్చరికలు ఇక్కడ కనిపిస్తాయి.',
    corridor: 'నడిచే దారి', corridorHint: '1 మీ వెడల్పు, 4 మీ ముందు వరకు. ఖాళీ గుర్తులు గుర్తుంచుకున్న ప్రమాదాలు.',
    helperView: 'సహాయకుడి కోసం కెమెరా దృశ్యం',
    tabs: ['నడక', 'చోట్లు', 'జ్ఞాపకం', 'సెట్టింగ్స్'],
    placesTitle: 'సేవ్ చేసిన చోట్లు', placesEmpty: 'ఇంకా చోట్లు లేవు. మీరు తరచూ వెళ్ళే చోటుకి చేరుకుని, పేరుతో సేవ్ చేయండి.',
    placeName: 'ఈ చోటు పేరు', save: 'సేవ్', guideMe: 'అక్కడికి తీసుకెళ్ళు', guiding: 'దారి చూపిస్తోంది:', stopGuide: 'దారి చూపడం ఆపండి',
    memoryTitle: 'గుర్తుంచుకున్న ప్రమాదాలు', hazardsN: 'ప్రమాదాలు', placesN: 'చోట్లు', pathPoints: 'దారి బిందువులు',
    memEmpty: 'ఇంకా ఏ ప్రమాదమూ గుర్తులేదు. కర్ర ప్రమాదాన్ని గుర్తించగానే ఇది ఆటోమేటిక్‌గా చేరుతుంది.',
    seen: (n) => `${n} సార్లు కనిపించింది`, risk: 'ప్రమాద స్థాయి', itsGone: 'తొలగింది',
    routeTitle: 'దారి:', shortest: 'అతి చిన్నది', safest: 'అతి సురక్షితం', metres: 'మీ',
    settingsTitle: 'సెట్టింగ్స్', language: 'భాష', speechRate: 'మాట్లాడే వేగం', vibration: 'హెచ్చరికపై వైబ్రేషన్',
    demoMode: 'డెమో మోడ్', demoHint: 'కర్ర లేకుండా, నమూనా డేటాతో యాప్‌ను ప్రయత్నించండి.',
    research: 'పరిశోధన మోడ్', researchHint: 'నడుస్తూ నిజమైన పరిస్థితిని ఎంచుకోండి. న్యూరల్ నెట్‌వర్క్ దీని నుండి నేర్చుకుంటుంది.',
    labels: ['సురక్షితం', 'జాగ్రత్త', 'హెచ్చరిక', 'అత్యవసరం'], rows: (n) => `${n} వరుసలు`,
    exportCsv: 'శిక్షణ డేటా డౌన్‌లోడ్', exportMem: 'జ్ఞాపకం డౌన్‌లోడ్',
    resetMemory: 'జ్ఞాపకాన్ని తొలగించండి', resetConfirm: 'అన్ని ప్రమాదాలు, చోట్లు, దారులు తొలగిపోతాయి.',
    cancel: 'రద్దు', confirmErase: 'తొలగించు', chooseLanguage: 'మీ భాషను ఎంచుకోండి', example: 'ఉదాహరణ',
    away: (m) => `${m} మీ దూరం`, ahead: 'ముందు', left: 'ఎడమ', right: 'కుడి',
    justNow: 'ఇప్పుడే', minAgo: (n) => `${n} నిమిషాల క్రితం`, hrAgo: (n) => `${n} గంటల క్రితం`, dayAgo: (n) => `${n} రోజుల క్రితం`,
    cat: { drop: 'గుంత/దిగువ', raised: 'ఎత్తు', static: 'అడ్డంకి', head: 'తల ఎత్తు', moving: 'కదిలేది', zone: 'ప్రాంతం' },
    model: 'ఫ్యూజన్ నెట్‌వర్క్', modelOn: 'న్యూరల్ నెట్‌వర్క్ పనిచేస్తోంది', modelOff: 'నియమాలు మాత్రమే',
    connection: 'కనెక్షన్', fps: 'ఫ్రేమ్‌లు/సె',
  },
  ta: {
    tagline: 'நினைவில் வைக்கும் கைத்தடி',
    connected: 'கைத்தடி இணைந்தது', demo: 'டெமோ', offline: 'கைத்தடி இணையவில்லை',
    demoBanner: 'டெமோ முறை: மாதிரித் தரவு. உண்மையாகப் பயன்படுத்த உங்கள் கைத்தடியை இணைக்கவும்.',
    start: 'நடக்கத் தொடங்கு', stop: 'நடையை நிறுத்து',
    pathClear: 'வழி தெளிவாக உள்ளது', levels: ['தெளிவு', 'கவனம்', 'எச்சரிக்கை', 'நில்லுங்கள்'],
    whereAmI: 'நான் எங்கே இருக்கிறேன்?', savePlace: 'இடத்தைச் சேமி', hazardGone: 'ஆபத்து நீங்கியது',
    recentAlerts: 'சமீபத்திய எச்சரிக்கைகள்', noAlerts: 'நீங்கள் கேட்கும் எச்சரிக்கைகள் இங்கே தெரியும்.',
    corridor: 'நடைப் பாதை', corridorHint: '1 மீ அகலம், 4 மீ முன்னால் வரை. வெற்றுக் குறிகள் நினைவில் உள்ள ஆபத்துகள்.',
    helperView: 'உதவியாளருக்கான கேமரா காட்சி',
    tabs: ['நடை', 'இடங்கள்', 'நினைவகம்', 'அமைப்புகள்'],
    placesTitle: 'சேமித்த இடங்கள்', placesEmpty: 'இன்னும் இடங்கள் இல்லை. நீங்கள் அடிக்கடி செல்லும் இடத்தை அடைந்து, பெயருடன் சேமிக்கவும்.',
    placeName: 'இந்த இடத்தின் பெயர்', save: 'சேமி', guideMe: 'அங்கே அழைத்துச் செல்', guiding: 'வழிகாட்டுகிறது:', stopGuide: 'வழிகாட்டலை நிறுத்து',
    memoryTitle: 'நினைவில் உள்ள ஆபத்துகள்', hazardsN: 'ஆபத்துகள்', placesN: 'இடங்கள்', pathPoints: 'வழிப் புள்ளிகள்',
    memEmpty: 'இன்னும் எந்த ஆபத்தும் நினைவில் இல்லை. கைத்தடி ஆபத்தைக் கண்டதும் தானாகச் சேர்க்கப்படும்.',
    seen: (n) => `${n} முறை பார்க்கப்பட்டது`, risk: 'ஆபத்து நிலை', itsGone: 'நீங்கியது',
    routeTitle: 'வழி:', shortest: 'மிகக் குறுகியது', safest: 'மிகப் பாதுகாப்பானது', metres: 'மீ',
    settingsTitle: 'அமைப்புகள்', language: 'மொழி', speechRate: 'பேச்சு வேகம்', vibration: 'எச்சரிக்கையில் அதிர்வு',
    demoMode: 'டெமோ முறை', demoHint: 'கைத்தடி இல்லாமல், மாதிரித் தரவுடன் செயலியை முயற்சிக்கவும்.',
    research: 'ஆய்வு முறை', researchHint: 'நடக்கும்போது உண்மையான நிலையைத் தேர்ந்தெடுக்கவும். நியூரல் நெட்வொர்க் இதிலிருந்து கற்கிறது.',
    labels: ['பாதுகாப்பு', 'கவனம்', 'எச்சரிக்கை', 'அவசரம்'], rows: (n) => `${n} வரிசைகள்`,
    exportCsv: 'பயிற்சித் தரவைப் பதிவிறக்கு', exportMem: 'நினைவகத்தைப் பதிவிறக்கு',
    resetMemory: 'நினைவகத்தை அழி', resetConfirm: 'நினைவில் உள்ள எல்லா ஆபத்துகளும் இடங்களும் வழிகளும் அழிக்கப்படும்.',
    cancel: 'ரத்து', confirmErase: 'அழி', chooseLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', example: 'உதாரணம்',
    away: (m) => `${m} மீ தொலைவில்`, ahead: 'முன்னால்', left: 'இடது', right: 'வலது',
    justNow: 'இப்போது', minAgo: (n) => `${n} நிமிடம் முன்`, hrAgo: (n) => `${n} மணி முன்`, dayAgo: (n) => `${n} நாள் முன்`,
    cat: { drop: 'குழி/இறக்கம்', raised: 'உயரம்', static: 'தடை', head: 'தலை உயரம்', moving: 'நகர்வது', zone: 'பகுதி' },
    model: 'ஃப்யூஷன் நெட்வொர்க்', modelOn: 'நியூரல் நெட்வொர்க் இயங்குகிறது', modelOff: 'விதிகள் மட்டும்',
    connection: 'இணைப்பு', fps: 'பிரேம்/வி',
  },
};

export const u = (key, ...args) => {
  const v = UI[getLang()][key] ?? UI.en[key];
  return typeof v === 'function' ? v(...args) : v;
};

export function ago(ts) {
  const s = (Date.now() - ts) / 1000;
  if (s < 60) return u('justNow');
  if (s < 3600) return u('minAgo', Math.round(s / 60));
  if (s < 86400) return u('hrAgo', Math.round(s / 3600));
  return u('dayAgo', Math.round(s / 86400));
}
